---
driver:
  name: vagrant

driver_config:
  requre_chef_omnibus: true
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]
  - ["private_network", {ip: "33.33.33.11"}]
  customize:
    memory: 2048
    cpus: 2
  cache:
    scope: :box

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
    attributes:
      postgres:
        version: "9.3"
  - name: centos-6.5
    run_list:
      - recipe[yum]

suites:
  - name: default
    data_bags_path: data_bags
    run_list:
      - recipe[emacs]
      - recipe[supermarket::default]
    attributes:
      postgres:
        auth_method: trust
